sudo: required
services: 
    - docker

before_install:
    - docker build -t amithraj1989/docker-react -f Dockerfile.dev .

script:
    - docker run amithraj1989/docker-react npm run test -- --coverage
    # - docker run -e CI=true USERNAME/docker-react npm run test
